# Scraping Settings
scraping:
  default_timeout: 30
  max_retries: 3
  rate_limits:
    news: 1  # requests per second
    reddit: 2
    twitter: 5
    quora: 1
    youtube: 3
    blog: 1
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"

# Analysis Settings
analysis:
  relevance:
    min_score: 0.6
    max_distance: 0.8
  sentiment:
    model: "distilbert-base-uncased-finetuned-sst-2-english"
    batch_size: 32
  credibility:
    min_score: 0.5
    fact_check_apis:
      - "google_fact_check"
      - "open_sources"
  clustering:
    algorithm: "kmeans"
    max_clusters: 10
    min_cluster_size: 3

# Output Settings
output:
  default_format: "markdown"
  available_formats:
    - "markdown"
    - "pdf"
    - "json"
  report:
    max_summary_length: 500
    include_sources: true
    include_metrics: true

# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/factryl.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Cache Settings
cache:
  enabled: true
  type: "redis"
  ttl: 3600  # 1 hour
  max_size: 1000  # entries 